### ISSUE TITLE
director.csv与district.csv数据重复了

### ISSUE THREAD

**Issue by GDongLin** [Linusp/kg-example#1]
![image](https://user-images.githubusercontent.com/19681333/71705027-6530a100-2e18-11ea-8ebb-cdf608308d70.png)
![image](https://user-images.githubusercontent.com/19681333/71705031-6f529f80-2e18-11ea-983c-7f91e77e6b64.png)
Halo，感谢提供了这份优质数据，但在使用过程中发现director.csv与district.csv数据重复了，可否重新上传正确的数据？谢谢。

{
    "entity-data": {
        "Person": "Person.csv",
        "Movie": "Movie.csv",
        "Country": "Country.csv"
    },
    "relation-data": {
        "Movie|actor|Person": "actor.csv",
        "Movie|composer|Person": "composer.csv",
        "Movie|director|Person": "director.csv",
        "Movie|district|Country": "district.csv"
    }
}

**Comment by Linusp** [comment]
抱歉，一直没注意到这个 issue，不知道是我漏看了还是没有发到我邮箱。我近期会重传一份数据（虽然不知道您是否还有需求），感谢反馈！

**Comment by Linusp** [comment]
@GDongLin 我检查了数据，并不存在重复问题，你的截图也没有显示数据有重复，两张截图中的 `START_ID` 有重复是正常现象。

这个 issue 我将关闭，如有其他问题可以再交流。
